language: go
go:
- '1.4'
before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username bloomapi --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
